### ISSUE TITLE
Model training gode

### ISSUE THREAD

**Issue by find1dream** [zhang943/lpn-pytorch#1]
Can you upload the training code for this amazing work? Thanks!

**Comment by iizukak** [comment]
I also want to try training LPN-50.
Training code is from `HRNet` ?

https://github.com/leoxiaobin/deep-high-resolution-net.pytorch/tree/master/tools

**Comment by zhang943** [comment]
Yes, the training code is from [HRNet](https://github.com/leoxiaobin/deep-high-resolution-net.pytorch/tree/master/tools).
