### ISSUE TITLE
the code of Iterative Training Strategy

### ISSUE THREAD

**Issue by ysq319** [zhang943/lpn-pytorch#2]
where is the code of Iterative Training Strategy,  and  how many steps is the appropriate choise？

**Comment by avnhungnh** [comment]
I think the Iterative training strategy is that you repeat the training process by choosing the best model in the previous stage as the weight initialization.

**Comment by ysq319** [comment]
> 我认为迭代训练策略是您通过选择上一阶段的最佳模型作为权重初始化来重复训练过程。

**Comment by ysq319** [comment]
> I think the Iterative training strategy is that you repeat the training process by choosing the best model in the previous stage as the weight initialization.

Thanks, i got it！
